### ISSUE TITLE
Update autogenerated docs

### ISSUE THREAD

**Issue by riga** [columnflow/columnflow#138]
Some functions / classes are not yet documented with docstrings and some are even missing in the automatic listing generated for our [rtd](http://columnflow.readthedocs.io) page.

Perhaps we should also add task documentation to these pages.

**Comment by pkausw** [comment]
Hi, I started working on this last week on the branch feature/documentation_docstrings. Sofar, I started with the `calibration` modules, let me know what you think :+1: 

Just fyi: I wanted to test if the internal/external linking works correctly, so I set up a workflow that publishes the docs on the GitHub Pages. This is obviously just a hacky workaround, I don't mean to propose to move away from readthedocs. I just couldn't figure out how to include additional branches there :D

**Comment by pkausw** [comment]
A rudimentary version of these docs are now in place with PR #386. These will need to improve, but I think we can already close this issue. Do you agree @riga ?
