### ISSUE TITLE
Add task and functions to create ML training plots

### ISSUE THREAD

**Issue by riga** [columnflow/columnflow#195]
We need a task and a couple associated plot functions to create plots showing results of ML trainings. Some ideas:

- Output distribution plots
- Classification plots
  - (multi-)ROC plots
  - Confusion matrices for multi-class trainings

Development already started in [feature/ml_plotting](https://github.com/uhh-cms/columnflow/tree/feature/ml_plotting).

**Comment by mafrahm** [comment]
This issue has been resolved with https://github.com/columnflow/columnflow/pull/341
