### ISSUE TITLE
Catch error when forgetting process_name, but not dataset_name.

### ISSUE THREAD

**Issue by Bogdan-Wiederspan** [columnflow/columnflow#235]
When a `dataset_name` is set, but forgotten in `process_names`, then a wrong processID is used in [`normalization_weights_setup()`](https://github.com/columnflow/columnflow/blob/master/columnflow/production/normalization.py)

To be more specific it happens within the for loop:
```
max_id = max(process_inst.id for process_inst in process_insts)
sum_weights_table = sp.sparse.lil_matrix((1, max_id + 1), dtype=np.float32)
for process_id, sum_weights in selection_stats["sum_mc_weight_per_process"].items():
        sum_weights_table[0, int(process_id)] = sum_weights  # error happens here
```

The error is not always triggered for example: 
```
dataset_names = ["graviton_hh_ggf_bbtautau_m1250_madgraph", "graviton_hh_vbf_bbtautau_m400_madgraph"]
process_names= ["graviton_hh_ggf_bbtautau_m1250"]
```
will trigger the error.

The reason for this is, that max_id is set using the `process_names` processID, but the value of processID is coming from the entry in `dataset_name`. Therefore a table is created with a smaller number of columns than necessary. 

I think we should catch this error, since the error message is not corresponding at all with the actual problem.

**Comment by pkausw** [comment]
Thanks for caching this @Bogdan-Wiederspan ! Maybe we should check explicitly whether a requested dataset is tied to a process (and vice versa) known within the analysis config to circumvent this
