### ISSUE TITLE
Fix range of color scale in 2D plots

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#241]
When comparing 2D distributions of different processes, it is sometime beneficial to use the same z-axis range on both of them (makes the comparison easier). Currently, this is not possible since the z-axis is derived on a per-histogram basis and the range settings aren't accessible to the user.

It would be nice to change this, i.e. give the `PlotVariables2D` task an additional option to set the z-axis range. Additionally, we could also think about giving the `PlotVariables2DPerProcess` task an option to fix the scale automatically, e.g. check the histograms in the current task call, derive the maximum z-range and use that for all calls of `PlotVariables2D` for the different processes

**Comment by mafrahm** [comment]
Hi @pkausw, the `zlim` parameter introduced in #238 will allow you setting the z-axis as required.

However, I feel like the second request to automatically fix the scale is not really possible to implement in the current task structure, since it would require some cross-communication between different `cf.PlotVariables2D` tasks.

Are you satisfied with the changes from #238 or shall we keep this issue open?

**Comment by pkausw** [comment]
Hey @mafrahm 

you're right, this new feature does include the first part of the request of this feature. However, I do think that the automization between processes should be possible. 

In my mind, the `PlotVariables2DPerProcess` task is basically a wrapper task that has all the required information available. With the changes introduces in #238 , we'd just need some logic that extracts the value ranges for the requested variables for the different processes, calculates the min/max values based on that and then set the z-axis in the individual `PlotVariables2D` tasks accordingly. 

Maybe this is wrong though, so feel free to correct me! If it is possible, then I would leave this issue open to keep track of the development.

**Comment by riga** [comment]
Has this issue been resolved, or should be add a "wontfix(fornow)" label?

**Comment by mafrahm** [comment]
Hi @pkausw, I will close this issue, since there is currently no way to implement the requested feature with our workflow.
