### ISSUE TITLE
Modifying local repo files interferes with remote jobs

### ISSUE THREAD

**Issue by dsavoiu** [columnflow/columnflow#279]
We are seeing an issue in our `mttbar` analysis setup, with jobs submitted to the _HTCondor_ batch system beginning to fail whenever any file in the local repository is modified. I'm describing our workflow below to illustrate the problem

We first submit a task to the batch system with `--workflow htcondor` (we also set `htcondor_share_software = True` in the law config, which may be relevant here). The `cf.BundleRepo` task is then scheduled, runs, and uploads an archive of the repository to the configured storage, and the actual taks scheduling and job submision then goes on as expected:
```
$ law run cf.ProduceColumns ... --workflow htcondor

INFO: luigi-interface - [pid 40097] Worker Worker(salt=8640385522, workers=1, host=naf-cms16.desy.de, username=<redacted>, pid=40097) running   cf.BundleRepo(include_files=, custom_checksum=NO_STR, source_path=NO_STR, analysis=mtt.config.analysis_mtt.analysis_mtt, replicas=5)

uploaded mttbar.c0d3955abbc7876c70bd12f438321ae57832def3.0.tgz
[...other replicas...]

going to submit 1 htcondor job(s), run2_2017_nano_v9_limited, st_tchannel_tbar_powheg
submitted 1/1 job(s)
submitted 1 job(s), run2_2017_nano_v9_limited, st_tchannel_tbar_powheg
18:59:23: all: 1, pending: 0 (+0), running: 1 (+1), finished: 0 (+0), retry: 0 (+0), failed: 0 (+0), run2_2017_nano_v9_limited, st_tchannel_tbar_powheg
```

If no further action is taken, the jobs finish successfully. However, if at any point a file in the analysis repository is modified, the jobs start failing. This can be any file, in particular also a file that is not tracked by git. The task status message reads:
```
19:00:24: all: 1, pending: 0 (+0), running: 0 (-1), finished: 0 (+0), retry: 1 (+1), failed: 0 (+0), run2_2017_nano_v9_limited, st_tchannel_tbar_powheg
1 failed job(s) in task cf.ProduceColumns_mtt_config_analy__1__87146dcf1d:
    job: 1, branch(es): [0], id: 12781840.0, status: retry, code: 20, error: undefined, job script error: bootstrap file failed,
    log: <path_redacted>/data/mtt_store/analysis_mtt/cf.ProduceColumns/run2_2017_nano_v9_limited/st_tchannel_tbar_powheg/nominal/calib__skip_jecunc/sel__default/prod__default/v2/stdall_0To1.txt
```

And the log file contains the following error message:
```
-- setup -------------------------------------------------------------------------------------------

-- bootstrap file
run bootstrap file 'remote_bootstrap_3c46256fbf.sh'
found existing software at <path_redacted>/data/software
law_wlcg_get_file: could not determine file to load from '<path_redacted>/data/mtt_store/analysis_mtt/cf.BundleRepo'
with file name 'mttbar.90a067047cf104212683d528ae8cfae7f7f3e4d3.[^\.]+.tgz'
bootstrap file failed with code 1, stop job
...

-- end ---------------------------------------------------------------------------------------------
...
job exit code : 20
```

Note the mismatched repo hash at submission time (`c0d3955`) and execution time (`90a0670`).

Is this expected behavior? It seems to me like this would negatively affect users developing code while running jobs out of the same repository, which should be a common enough use case.

I would also argue that some sort of persistence mechanism is needed so the bootstrap script running on the remote does not rely on the current state of the repository (even with `htcondor_share_software = True`) to calculate the hash for the repo image, but I am not familiar enough with the bootstrap script/bundling mechanism to understand how this could be implemented. Maybe @riga can help here?

As a partial fix, one could at least exclude untracked files from the checksum calculation. I'm actually a bit puzzled about the reasoning to include them in the first place, since as far as I can tell, only tracked files are actually added to the repo image, so the hash would change even if the content does not. This seems counterintuitive to me, but it's entirely possible that I'm missing something.

**Comment by mafrahm** [comment]
Hi @dsavoiu, this is an issue I had as well. One workaround would be to just set a custom checksum via the `--custom-checksum` parameter. In that way you can store one specific version of you repo with the `cf.BundleRepo` task and use that for task submission while working on other things.

**Comment by dsavoiu** [comment]
Hi @mafrahm, that's a good tip, thanks! It is certainly nice to have `--custom-checksum` as a workaround, but that would of course require running `cf.BundleRepo` manually, which is not ideal from a user experience point of view. Let's keep the issue open in case we find a way to fix the underlying cause, but I'll maybe tag this as `priority-low` now that a workaround is documented.

**Comment by mafrahm** [comment]
Hi @dsavoiu, you don't need to run cf.BundleRepo manually, you just need to add `cf.BundleRepo-custom-checksum <name>` to whatever you want to submit with your current repo.

However, I agree with you that we should still try and find a better solution for this issue.

**Comment by dsavoiu** [comment]
> Hi @dsavoiu, you don't need to run cf.BundleRepo manually, you just need to add `--cf.BundleRepo-custom-checksum <name>` to whatever you want to submit with your current repo.

I see, so you can choose whatever string you like for `<name>`, and that will be used to identify the repo instead of the actual checksum? I thought one needed to use the actual checksum for the repo, which is why I assumed that `cf.BundleRepo` should be run beforehand. But if the user-defined `--custom-checksum` is used consistently both on the submission side and the worker node, your suggestion should indeed be sufficient.
