### ISSUE TITLE
Minimal example seems not to work / ProduceColumns fails

### ISSUE THREAD

**Issue by tolange** [columnflow/columnflow#289]
Hi :) As I am new to this I tried the minimal example from the readme, but when it comes to plotting variables the ProduceColumns task always fails as some keys are missing in a dictionary. Looking through the code it seems it should be added with: https://github.com/columnflow/columnflow/blob/a812d032db9e753de886e92e86d34baed7eec341/columnflow/selection/stats.py#L27-L196 but isn't.
Not sure if this is a problem with the code or the readme need to be updated as the task requires an additional argument?

<img width="1316" alt="Screenshot 2023-08-23 at 13 36 39" src="https://github.com/columnflow/columnflow/assets/11850680/be3dbfed-23e2-48cd-9ce3-ad7e54fce051">

**Comment by tolange** [comment]
<img width="1284" alt="Screenshot 2023-08-23 at 13 42 28" src="https://github.com/columnflow/columnflow/assets/11850680/d40e1914-1a61-4906-8c2f-cd63d7148ff9">
It seems all information split by process is missing. (printing selection_stats)

**Comment by pkausw** [comment]
Hi @tolange , thanks for the feedback! Indeed, we have also found this issue and opened basically the same issue at the same time as you. For simplicitly, I think it's better to track this in #290 (which also contains a workaround for now). Would it be alright with you if I close this issue to make keeping track easier?

**Comment by tolange** [comment]
Yes, and thank you @pkausw :)
