### ISSUE TITLE
Software setup breaks on zsh

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#295]
After the recent updates to fix issues with the skeleton analysis, I tried setting one up within a zsh shell. Everything works fine, until cf tries to install the default dev environment:

```
installing venv cf_dev from /nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/sandboxes/cf_dev.sh at /nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c
Requirement already satisfied: pip in /nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages (23.0.1)
Collecting pip
  Using cached pip-23.2.1-py3-none-any.whl (2.1 MB)
Requirement already satisfied: setuptools in /nfs/dust/cms/user/pkeicher/cf_cache/software/venvs/cf_dev_9b04c75c/lib/python3.9/site-packages (58.1.0)
Collecting setuptools
  Using cached setuptools-68.1.2-py3-none-any.whl (805 kB)
Installing collected packages: setuptools, pip
  Attempting uninstall: setuptools
    Found existing installation: setuptools 58.1.0
    Uninstalling setuptools-58.1.0:
      Successfully uninstalled setuptools-58.1.0
  Attempting uninstall: pip
    Found existing installation: pip 23.0.1
    Uninstalling pip-23.0.1:
      Successfully uninstalled pip-23.0.1
Successfully installed pip-23.2.1 setuptools-68.1.2
install pip
add_requirements:local:1: not valid in this context: /nfs/dust/cms/user/pkeicher/uhh/podas/hto4l/modules/columnflow/sandboxes/cf.txt

```

I found [this](https://unix.stackexchange.com/questions/208607/zsh-export-not-valid-in-this-context) and [this](https://unix.stackexchange.com/questions/68694/when-is-double-quoting-necessary/68748#68748) article, and have the impression that the issue arises because of [this line](https://github.com/columnflow/columnflow/blob/master/sandboxes/_setup_venv.sh#L263). Commenting it out and replacing the `args` variable with the `@` fixed the issue for me (though I see other error regarding some of the cf color commands that don't stop anything though).

Nevertheless, I think this is just a temporary workaround, and we should try to find a more permanent solution.

**Comment by riga** [comment]
In the zsh version that is predominantly used on our machines (e.g. naf, lxplus), assigning `$@` to a local variable does not work on the same line, i.e.,

```shell
local args="$@"

# must become
local args
args="$@"
```

I enforced this throughout cf, plus some other compatibility hacks in 38d96c0.
