### ISSUE TITLE
A few issues with adding and plotting new columns

### ISSUE THREAD

**Issue by gsaha009** [columnflow/columnflow#299]
Hello Columnflow developers,

Following the conversations in issues #291  and #294 , the skeleton analysis framework seems to be working fine. Nevertheless, there are certain challenges I've encountered that may not be attributed to framework issues. So, I am not certain whether this is the appropriate platform for addressing those issues. However, I have outlined several points below

 - Is it possible to add some new columns in any selector module and then use those in a producer? From my understanding based on the [HHbbWW](https://github.com/uhh-cms/hh2bbww) and [Topmass](https://github.com/uhh-cms/topmass) analyses, it is possible. However, in my skeleton analysis, I added a new column `channel_id` in my lepton-selector module. Unfortunately, I encountered difficulties in using it in a producer module. It showed that the column was not found. I defined a new category based on the same and I noticed similar error. 
 - Is it possible to plot any new column saved in the selection step? I tried to add a variable `m_ll` (invariant mass of two leptons) in the lepton selection module, but the column was not found at the plotting stage. It also showed some error like `awkward._errors.FieldNotFoundError: no field 'm_ll' in record with 4 fields. This error occurred while attempting to slice <Array [{category_ids: [...], ...}, ...] type='74929 * {category_ids: v...'> with 'm_ll'`.
 - In the main analysis config, I think it is mandatory to mention the name of the columns that one wants to perform their analysis with. But, I was a bit confused why several columns were mentioned in two dictionaries: `cf.ReduceEvents` and ` cf.MergeSelectionMasks`!!
 - Is there any particular order that the columnflow modules do follow? It appears that I can call a producer in a selector if I want to make some selection based on any custom-made variable. Likewise, if I am not wrong, it also seems possible to call a producer within a calibrator module!!
 - Is it possible to use the selection result further in other producer modules? To give a specific example, let’s say I save lepton pairs as `auxiliary` in the selection results, and after that, can I use that in a subsequent producer to create additional columns containing dilepton-features?

I want to emphasize that these doubts may arise due to potential gaps in my fundamental understanding of the ColumnFlow framework. However, it would be extremely helpful if you could provide any insights or clarification on the points I've raised above. 

Thank you very much.

Gourab 

[* Working directory: https://github.com/gsaha009/HCPToTauTau/tree/DYdev]

**Comment by mafrahm** [comment]
Hey @gsaha009,are you listing the columns you want to plot in the `keep_columns` dictionary (e.g. [here](https://github.com/columnflow/columnflow/blob/d59cc33de9db650a0411fac2d1ef954e73299ccf/analysis_templates/cms_minimal/__cf_module_name__/config/analysis___cf_short_name_lc__.py#L229))?

In that dictionary, there are multiple keys, to allow you to decide whether you want to use a column as part of some cutflow studies (after the `cf.MergeSelectionMasks` task) or if you want to keep these columns after applying your event selections (after `cf.ReduceEvents`). That means if you want to create a plot with the `cf.PlotCutflowVariables1D` task, your variable needs to be listed under the `cf.MergeSelectionMasks` key. And if you need the variable after your event selection, it needs to be listed under the `cf.ReduceEvents` key.

Regarding you 4th question, the full task graph can be found here: https://github.com/columnflow/columnflow/wiki
We directly call a Calibrator in `cf.CalibrateEvents`, a Selector in `cf.SelectEvents` and a Producer in `cf.ProduceColumns`. But these functions are modular, which allows you to call a Producer as part of another CSP (Calibrator/Selector/Producer).

Regarding your final questions, here is an example, where I'm doing what you're asking for: [hbw/selection/cutflow_features.py](https://github.com/uhh-cms/hh2bbww/blob/488c8a4b65e49ad22a33092e6128164c93c79a92/hbw/selection/cutflow_features.py#L32)

This is a Producer which I'm calling as part of my event selection to produce some simple cutflow features. This, however, only works when calling the Producer inside the Selector.
After the `cf.SelectEvents` task, we only use the `SelectionResult` steps and objects to apply our events and object definition. The `auxiliary` part of the `SelectionResult` is specifically thought as a way to store columns during the event selection which you do not intent to store afterwards.

I hope I answered all of your questions. Feel free to ask again if anything is left unclear.

Cheers,
Mathis

**Comment by gsaha009** [comment]
Hi @mafrahm 
Thanks a lot for this detailed response. Yes, it contains all the explanations I was looking for. 
:) :)

**Comment by mafrahm** [comment]
Hey @gsaha009, at the moment, the `events` arrays can only be stored as parquet files. There is only the [union](https://github.com/columnflow/columnflow/blob/master/columnflow/tasks/union.py) task, which merges columns from `ReduceEvents`, `ProduceColumns` and `MLEvaluation`, but outputs are again only stored as parquet files. It might be a good idea to generalize this task to allow different output formats.

**Comment by gsaha009** [comment]
Hi @mafrahm 
Thanks a lot for all the answers :)
