### ISSUE TITLE
Optimize compression for parquet files

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#309]
Recently, users tried to process very large NanoAOD sample, e.g. the `TTToHadron` sample which has a size of ~1TB. In this case, the user only had a limited amount of disk space available (also ~1TB), and this space completely ran out during the CalibrateEvents task.

Further studies have shown that the original NanoAOD .root files with the full set of information is of order ~700MB/file. The corresponding parquet files from the CalibrateEvents task are of order ~500MB/file, although they only contain a fraction of the information (~128 columns with `float32` or `uint64`). Essentially, we almost double the size of a NanoAOD sample in the CalibrateEvents task. Maybe we can further optimize this with different compression rates?

**Comment by riga** [comment]
We can try looking into better compression and make choices optional through the law.cfg per task, similar to how exact storage locations per task are defined.

In the meantime, are you generating too many uncertainties that you possibly might not need? For instance, the default jec calibrator creates `mass` and `pt` for each jet, in the nominal "variation" and twice per shift that is registered in the correctionlib file. I suspect that all of these shifts are not required at an early prototyping stage.

**Comment by pkausw** [comment]
That is surely true - currently we don't need all the variations. I just thought that since we saw sth like this and there _might_ be an analysis in the future that also needs the full set of uncertainties, it would be good to look into this earlier rather than later. But I also think that there are more pressing matters before we have to look into this one

**Comment by mafrahm** [comment]
I assume your timings are regarding the write times, where differences between SNAPPY and ZSTD1 are negligible. Do we expect differences in the read time?

**Comment by riga** [comment]
Decompression is even faster.

I ran `CalibrateEvents` with SNAPPY and ZSTD(1) compression on a nano input file with 626k events, and then `SelectEvents` in a single thread and measured only the decompression and IO read time.

- Compression sizes:
  - SNAPPY: 1,148 GB
  - ZSTD(1): 1,051 GB
  - → ZSTD(1) file 8.4% smaller
- Compression times:
  - SNAPPY: 15.5 s
  - ZSTD(1) 17.2 s
  - → SNAPPY faster
- Decompression times:
  - SNAPPY 7.9 s
  - ZSTD(1) 4.8 s
  - → ZSTD(1) faster

So ZSTD(1) indeed seems like a good choice here.
