### ISSUE TITLE
Fix build documentation

### ISSUE THREAD

**Issue by nprouvost** [columnflow/columnflow#331]
The last changes in the documentation were not taken by the readthedoc webpage, build failed due to non-existent requirements_prod.txt file in the main directory of the repository. The error can be seen in the build history, e.g. https://readthedocs.org/projects/columnflow/builds/22342073/ and it seems that this specific requirement file is required by the docs/requirements.txt file. At some point in time (https://github.com/columnflow/columnflow/tree/e6ce4a31115b7b7ec9e3f949c4f70e336c443f06), the requirements_prod.txt file did contain dependencies like luigi, scinum, six, and pyyaml. Where are they from in the current workflow, such that the path can be adjusted? Or was this a requirement file created only for the documentation and needs to be recreated?

**Comment by nprouvost** [comment]
solved in https://github.com/columnflow/columnflow/commit/1b66136bdb6ec36b95559bcd0bebd9baf4693217 for the feature/docs_best_pratices branch

**Comment by riga** [comment]
Fixed in #332
