### ISSUE TITLE
Error in Module 'columnflow.tasks.{}': name 'producer' is not defined

### ISSUE THREAD

**Issue by JulesVandenbroeck** [columnflow/columnflow#359]
Hi everyone,

I received the following error while trying to `source setup.sh `, something I did not have before and I cannot backtrack what I did that could to cause this (I was working on making a machine learning model). 

[juvanden@m1 ttz]$ source setup.sh 
initialized conda with micromamba interface and python 3.9
error in module 'columnflow.tasks.framework': name 'producer' is not defined
error in module 'columnflow.tasks.calibration': name 'producer' is not defined
error in module 'columnflow.tasks.selection': name 'producer' is not defined
error in module 'columnflow.tasks.reduction': name 'producer' is not defined
error in module 'columnflow.tasks.production': name 'producer' is not defined
error in module 'columnflow.tasks.ml': name 'producer' is not defined
error in module 'columnflow.tasks.union': name 'producer' is not defined
error in module 'columnflow.tasks.histograms': name 'producer' is not defined
error in module 'columnflow.tasks.plotting': name 'producer' is not defined
error in module 'columnflow.tasks.yields': name 'producer' is not defined
error in module 'columnflow.tasks.cutflow': name 'producer' is not defined
error in module 'columnflow.tasks.cms.inference': name 'producer' is not defined
 
link to [project on gitlab](https://gitlab.cern.ch/juvanden/ttz)

**Comment by riga** [comment]
Hi @JulesVandenbroeck ,

at the end of the setup, your tasks are indexed once for shell auto-completion of the `law run ...` command. The error you're seeing is most likely caused by an error in your python code. You can run `law index --verbose` to see stack traces that help you debug.
