### ISSUE TITLE
plot-function parameter not usable in PlotCutflowVariables1D

### ISSUE THREAD

**Issue by mafrahm** [columnflow/columnflow#367]
In the PlotCutflowVariables1D task, the `plot-function` parameter is currently not usable. Instead, we provide two hard-coded plotting functions based on the `--per-plot` parameter [1]. We should allow custom plotting functions here and resolve the correct default based on the `steps` parameter only if no plotting function has been set.

[1] https://github.com/columnflow/columnflow/blob/master/columnflow/tasks/cutflow.py#L582

**Comment by riga** [comment]
Indeed. I think if a custom plot function is passed, we should use it independent of the `--per-plot` value, and by that assume the user is aware.
