### ISSUE TITLE
Different evaluations for one MLModel

### ISSUE THREAD

**Issue by mafrahm** [columnflow/columnflow#380]
Right now, we can only provide a single `evaluate` function for each MLModel class. However, there are some usecases (e.g. parametrized NN), where you train a single Model and then need to evaluate N times.
It might be good to provide some structure in columnflow to encode the different types of evaluations.

**Comment by mafrahm** [comment]
We have found a way around the problem by adding a separate Producer to the requirements when running the `cf.MLEvaulation` task:
```
# evaluate for masspoint 400
law run cf.MLEvaluation --version v1 --ml-model xy --producers default,m400
# evaluate for masspoint 500
law run cf.MLEvaluation --version v1 --ml-model xy --producers default,m500
```
This solution is not perfect since we need to run a separate Producer for each evaluation producing at least one column.

**Comment by pkausw** [comment]
Even though the solution is not perfect, it still works right? Can we close this issue @mafrahm ?

**Comment by mafrahm** [comment]
In my opinion, this issue can be closed now.
