### ISSUE TITLE
Making MergeReducedEvents optional

### ISSUE THREAD

**Issue by riga** [columnflow/columnflow#384]
In cases where merging is not required (e.g. if the files are so large that it would be 1-to-1 merging, of if it's simply not desired), it should be possible to skip it.

This is mean that subsequent tasks (UniteColumns, ProduceColumns, WriteHistograms, PrepareMLEvents, MLEvaluation) should have the option to directly retrieve their inputs from ReduceEvents.

This could be solved by having in intermediate wrapper-like task that provides the input with a clean interface, so that switches between different `requires()`/`input()` structures only exist once.

Also see https://github.com/columnflow/columnflow/discussions/383.

**Comment by mafrahm** [comment]
Closed by #388
