### ISSUE TITLE
support for containers

### ISSUE THREAD

**Issue by jpata** [columnflow/columnflow#398]
What are the plans to support running columnflow inside a container (e.g. apptainer)?
This is needed to deploy at various T2 sites, and also at most HPCs.

**Comment by pkausw** [comment]
Hi @jpata , sorry for the late reply. In principle, using containers is already possible via the corresponding law mechanism - maybe @riga can further comment on this.

We are also working on providing pre-built images for different python versions, and am currently working on restructuring the software setup procedure to this end. There is no specific timeline for this development yet, but it shouldn't take much longer at this point.

Does this answer your question? Do you have a specific problem/use case at hand right now?

**Comment by jpata** [comment]
What I see now is that when running the code, it starts to install various python environments locally via micromamba.
This may not always be desirable or possible in the user space.

For example, most HPC-s disallow creating local python environments in the user home dir (due to creating millions of small files for each user), but instead require the use of prepackaged containers.
Similarly at CMS T2-s, the minimum requirement for worker nodes is that they must have singularity and cvmfs, nothing else is really guaranteed and should not be relied on (e.g. minimum python versions from the system side).

So to deploy at other sites, it would be good if the tasks can optionally specify the software environment via a container, rather than requiring local installation of packages.

**Comment by pkausw** [comment]
I see. Just a quick follow up: The individual tasks can indeed specify their own software environment via the `sandbox` mechanism. You can also user docker/singularity images as sandboxes, so on a per-task level this is solved.

The most general software is indeed installed with micromamba. However, when running remote jobs via htcondor/slurm/crab, the software is first bundled into tar balls and then sent alongside the jobs, which means that remote jobs aren't required to install anything themselves but rather use the already bundled software. So long story short, the software is installed locally, but tasks that run on remote sides access pre-bundled software. You can find a dedicated section about the software mechanism in [the docs](https://columnflow.readthedocs.io/en/latest/user_guide/sandbox.html).

Does this answer your question?

**Comment by jpata** [comment]
Thanks for the reference. I didn't find any information in the docs on containers (docker* / singularity), which is why I originally made this issue. How would I go about configuring the tasks to use a specific container image, both on the interactive node and worker node?

* note that docker is also not usually allowed on HPC-s/T2-s due to requiring root privileges

**Comment by pkausw** [comment]
Hi @jpata , is there anything more regarding this issue? If not, I think we can close it
