### ISSUE TITLE
Problem with version fixing for MLTraining, MergeMLEvents, PrepareMLEvents

### ISSUE THREAD

**Issue by slavheatcliff8** [columnflow/columnflow#409]
Hi everyone, 

Columnflow seems to ignore version committing for MLtraining related tasks. After specifying versions in config, the framework ignores the config file and uses the version specified on the command line. 

**Config:**
![Снимок экрана 2024-02-29 в 15 57 22](https://github.com/columnflow/columnflow/assets/130742954/56ac578a-c6b1-43f3-b446-e827a5f6da24)

**Output from cf.CreateDatacards --print-deps --version test0**
<img width="1747" alt="image" src="https://github.com/columnflow/columnflow/assets/130742954/1d6068f9-e02c-4c24-8f17-253f69fc7c0e">

**Comment by riga** [comment]
Fixed in https://github.com/columnflow/columnflow/pull/449.
