### ISSUE TITLE
pip install is broken

### ISSUE THREAD

**Issue by TTF2050** [columnflow/columnflow#410]
When installing the prepackaged version via pip, `setup.py` refers to a file `requirements_prod.txt` that does not exist in the distribution tarball.

**Comment by pkausw** [comment]
Hi @TTF2050 , thanks for opening this issue. Can you give us more information about the system you use to set up your analysis? E.g. operating system, flavor of shell (e.g. bash or zsh), python version, ...

**Comment by TTF2050** [comment]
I'm using Ubuntu 22.04, python 3.10, and bash. But all of that is irrelevant. If you go to https://pypi.org/project/columnflow/, pull the tarball, and unpack it, you can see that the setup.py references a file that does not exist.

**Comment by pkausw** [comment]
Ah, thanks for the clarification. Indeed, this is correct and will be addressed with the next stable version that will come soon. We're also working on the general setup mechanism, which should also fix/improve this.

That being said: Please note that columnflow isn't really intended to act as a standalone package, but rather as a "backbone" for an analysis-specific setup. If you're trying to set up a new analysis, we recommend following the [Quickstart instructions](https://github.com/columnflow/columnflow?tab=readme-ov-file#quickstart). If you have a more specific use case in mind, let us know - we're always happy about feedback!

**Comment by TTF2050** [comment]
Honesty I found this accidentally while setting up the [D4RL](https://github.com/Farama-Foundation/D4RL) project.

**Comment by pkausw** [comment]
OK! I'm not entirely sure how the project you've linked relates to columnflow - while we do support ML applications as part of our task graph, we're not focused on reinforcement learning. Apart from the fact that we'll fix the version on pypi with the next release, it might help us to further understand what you would like to do if you gave us more background information.
