### ISSUE TITLE
cf.ProduceColumnsWrapper does not pick up correct default producer

### ISSUE THREAD

**Issue by maadcoen** [columnflow/columnflow#444]
I have a config called`myconfig` containing the line `config.x.default_producer = "myproducer"`. However, when running 

```law run cf.ProduceColumnsWrapper --datasets mydatasets --configs myconfig```

the task`cf.ProduceColumns` will run for each dataset with the producer `default`.  Adding the argument `--producers myproducer` fixes this issue, but this solution misses the point of having a default setting in the config. Another way of restoring the default behaviour, is by removing the added `producers` parameter in [columnflow/tasks/production.py](https://github.com/columnflow/columnflow/blob/master/columnflow/tasks/production.py#L174). But then the `--producers` argument is not available anymore.

**Comment by mafrahm** [comment]
Hi @maadcoen, I just checked this in my analysis and for me, the correct default Producer(s) are being picked. I might be that you have two different configs which define different default producers, but our wrapper task picks the default from one of the configs.

**Comment by riga** [comment]
@maadcoen Were you able to verify?

I did a second check and it should be working on the latest master.

**Comment by riga** [comment]
Closing this for now, but feel free to reopen if the issue persists!
