### ISSUE TITLE
Accidentally overwriting dynamic requirements from producers

### ISSUE THREAD

**Issue by mafrahm** [columnflow/columnflow#467]
When assigning dynamic requirements via Producers, there might be overlap in keys, which results in requirements being overwritten

https://github.com/columnflow/columnflow/blob/master/columnflow/production/normalization.py#L60

**Comment by riga** [comment]
This would be rather simple to achieve (possible patch below), but things would become a bit more messy as (e.g.) many producers require the same tasks (e.g. `BundleExternalFiles`), which would then appear multiple times in task dependency and status overviews.

I think we could streamline this at some point but for now, it might be too big of a deal for the sole purpose of convenience.

---

```diff
diff --git a/columnflow/columnar_util.py b/columnflow/columnar_util.py
index b738d4ce..fd830bde 100644
--- a/columnflow/columnar_util.py
+++ b/columnflow/columnar_util.py
@@ -2309,7 +2309,7 @@ class TaskArrayFunction(ArrayFunction):

         # run this instance's requires function
         if callable(self.requires_func):
-            self.requires_func(reqs)
+            self.requires_func(reqs.setdefault(self.cls_name, {}))

         # run the requirements of all dependent objects
         for dep in self.get_dependencies():
@@ -2342,7 +2342,7 @@ class TaskArrayFunction(ArrayFunction):

         # run this instance's setup function
         if callable(self.setup_func):
-            self.setup_func(reqs, inputs, reader_targets)
+            self.setup_func(reqs[self.cls_name], inputs[self.cls_name], reader_targets)

         # run the setup of all dependent objects
         for dep in self.get_dependencies():
```
