### ISSUE TITLE
cf.CreateYieldTable is not working

### ISSUE THREAD

**Issue by aalvesan** [columnflow/columnflow#491]
Independent to which categories are defined, the yield in the table is always shown as zero..

**Comment by mafrahm** [comment]
Hi @aalvesan, I cannot reproduce the issue. Are you sure that you pass the correct `category_ids` column when creating histograms?

**Comment by pkausw** [comment]
Hi @aalvesan @mafrahm , is this issue still on going? Has there been any progress?

**Comment by mafrahm** [comment]
I'll close this issue since as far as I know there is no framework-related issue. Feel free to reopen this issue or open a discussion if there are still any problems.
